feat: Add Dockerfile path detection and setup Docker Buildx in workflow

diff --git a/.github/workflows/dotnet-cd.yml b/.github/workflows/dotnet-cd.yml
--- a/.github/workflows/dotnet-cd.yml
+++ b/.github/workflows/dotnet-cd.yml
@@ -76,7 +76,6 @@ jobs:
     runs-on: ubuntu-latest
 #      group: CHQ
 #      labels: linux
-
     #runs-on: ubuntu-latest
 
     timeout-minutes: 45
@@ -91,7 +90,7 @@ jobs:
       NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: ${{ vars.NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS || '20' }}
       NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: ${{ vars.NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS || '20' }}
       REGISTRY: ghcr.io/xplor-pay
-      IMAGE_NAME: ${{ github.repository }}
+      IMAGE_NAME: ${{ github.event.repository.name }}
 
     steps:
     - name: Checkout Repository
@@ -104,6 +103,22 @@ jobs:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
 
+    - name: Find Dockerfile path
+      id: find-dockerfile
+      shell: bash
+      run: |-
+        DOCKERFILE_PATH=$(find . -type f -name Dockerfile -not -path "./.git/*" | head -n 1)
+        if [ -z "$DOCKERFILE_PATH" ]; then
+          echo "::error::No Dockerfile found in repository."
+          exit 1
+        fi
+        echo "dockerfilePath=$DOCKERFILE_PATH" >> "$GITHUB_ENV"
+        echo "dockerfile_path=$DOCKERFILE_PATH" >> "$GITHUB_OUTPUT"
+        echo "Dockerfile location: $DOCKERFILE_PATH"
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v4
+      
     - name: Extract Docker metadata
       id: meta
       uses: docker/metadata-action@v5
@@ -115,14 +130,12 @@ jobs:
           type=semver,pattern={{version}}
           type=sha,format=short
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v4
-      
     - name: Build and Push Docker Image
       id: build-and-push
       uses: docker/build-push-action@v3
       with:
         context: .
+        file: ${{ steps.find-dockerfile.outputs.dockerfile_path }}
         push: true
         tags: ${{ env.REGISTRY }}/${{ needs.setup.outputs.image_name }}:${{ needs.setup.outputs.dotnet_version }}-${{ needs.setup.outputs.version }}
 
